apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vps8150pi-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vps8150pi-nodejs 
  name: vps8150pi-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: vps8150pi-nodejs 
